name: build-ci

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    uses: kagekirin/gha-py-toolbox/.github/workflows/make-build.yml@main
    with:
      configurations: ${{ vars.BUILD_CONFIGURATIONS }}
      include: ${{ vars.BUILD_MATRIX }}
    secrets: inherit
