name: build-ci

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    uses: kagekirin/gha-py-toolbox/.github/workflows/make-build.yml@main
    with:
      configurations: ${{ vars.BUILD_CONFIGURATIONS }}
      include: ${{ vars.BUILD_MATRIX }}
    secrets: inherit


  unittests:
    needs:
    - build
    uses: kagekirin/gha-py-toolbox/.github/workflows/make-unittests.yml@main
    with:
      max-parallel: 4
      configurations: ${{ vars.TEST_CONFIGURATIONS }}
      commands: ${{ vars.TEST_COMMANDS }}
      include: ${{ vars.TEST_MATRIX }}
    secrets: inherit


  tag-release:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      packages: read
    needs:
    - build
    uses: kagekirin/gha-py-toolbox/.github/workflows/github-release.yml@main
    with:
      dry-run: false
    secrets: inherit


  package:
    permissions:
      contents: read
      packages: write
    needs:
    - build
    uses: kagekirin/gha-py-toolbox/.github/workflows/npm-pack.yml@main
    with:
      targets: ${{ vars.DEPLOY_TARGETS }}
      include: ${{ vars.DEPLOY_MATRIX }}
      package-json: package.json
    secrets: inherit
