name: build-branch

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: kagekirin/gha-py-toolbox/.github/workflows/make-build.yml@main
    with:
      configurations: ${{ vars.BUILD_CONFIGURATIONS }}
      include: ${{ vars.BUILD_MATRIX }}
    secrets: inherit


  test-tag-release:
    permissions:
      contents: write
      packages: read
    needs:
    - build
    uses: kagekirin/gha-py-toolbox/.github/workflows/make-release.yml@main
    with:
      dry-run: true
    secrets: inherit
